apiVersion: apps/v1
kind: Deployment
metadata:
  name: vericase-api
  namespace: vericase
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vericase-api
  template:
    metadata:
      labels:
        app: vericase-api
    spec:
      containers:
      - name: api
        image: wcjrogers/vericase-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
