-- Active: 1763739336777@@localhost@55432
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS attachments JSONB;
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS as_planned_date TIMESTAMP;
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS as_planned_activity VARCHAR(500);
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS as_built_date TIMESTAMP;
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS as_built_activity VARCHAR(500);
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS delay_days INTEGER DEFAULT 0;
ALTER TABLE evidence ALTER COLUMN delay_days SET DEFAULT 0;
UPDATE evidence SET delay_days = 0 WHERE delay_days IS NULL;
ALTER TABLE evidence ADD COLUMN IF NOT EXISTS is_critical_path BOOLEAN DEFAULT FALSE NOT NULL;
