ALTER TABLE cases ADD COLUMN IF NOT EXISTS case_id_custom VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS project_name VARCHAR(500);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS dispute_type VARCHAR(100);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE cases ADD COLUMN IF NOT EXISTS case_status VARCHAR(50);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS legal_team JSON;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS heads_of_claim JSON;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS deadlines JSON;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_cases_case_id_custom ON cases(case_id_custom);

