#!/bin/bash
# VeriCase EC2 Bootstrap Script
# Use as EC2 UserData when launching a new instance
#
# Instance requirements:
#   - Ubuntu 22.04 or Amazon Linux 2
#   - t3.medium or larger
#   - 30GB+ EBS storage
#   - Security group: 22 (SSH), 8010 (API), 9001 (MinIO)

exec > >(tee /var/log/vericase-bootstrap.log) 2>&1
set -e

echo "=========================================="
echo "VeriCase EC2 Bootstrap"
echo "Started: $(date)"
echo "=========================================="

# Configuration
GITHUB_REPO="https://github.com/williamcjrogers/VeriCaseJet.git"
APP_DIR="/opt/vericase"
AWS_REGION="eu-west-2"

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    OS="unknown"
fi

echo "Detected OS: $OS"

# Update system
echo "[1/7] Updating system..."
if [ "$OS" = "ubuntu" ]; then
    apt update && apt upgrade -y
    apt install -y git curl jq
elif [ "$OS" = "amzn" ]; then
    yum update -y
    yum install -y git curl jq
fi

# Install Docker
echo "[2/7] Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
fi

# Add user to docker group
if [ "$OS" = "ubuntu" ]; then
    usermod -aG docker ubuntu
elif [ "$OS" = "amzn" ]; then
    usermod -aG docker ec2-user
fi

# Install Docker Compose
echo "[3/7] Installing Docker Compose..."
if ! command -v docker-compose &>/dev/null; then
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
fi

# Install AWS CLI v2
echo "[4/7] Installing AWS CLI..."
if ! command -v aws &>/dev/null; then
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -q awscliv2.zip
    ./aws/install
    rm -rf aws awscliv2.zip
fi

# Clone repository
echo "[5/7] Cloning repository..."
mkdir -p $APP_DIR
cd $APP_DIR

if [ -d "VeriCaseJet" ]; then
    cd VeriCaseJet
    git pull origin main
else
    git clone $GITHUB_REPO
    cd VeriCaseJet
fi

cd vericase

# Generate secure credentials
echo "[6/7] Generating credentials..."
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)

# Create .env file
cat > .env << EOF
# VeriCase Production Configuration
# Generated by EC2 bootstrap: $(date)

# API Settings
API_HOST=0.0.0.0
API_PORT=8000
CORS_ORIGINS=*

# Security
JWT_SECRET=$JWT_SECRET
JWT_ISSUER=vericase-pst-analysis
JWT_EXPIRE_MIN=7200

# Admin
ADMIN_EMAIL=admin@vericase.com
ADMIN_PASSWORD=$ADMIN_PASSWORD

# Database (local PostgreSQL in docker-compose)
DATABASE_URL=postgresql://vericase:vericase@postgres:5432/vericase

# Redis (local in docker-compose)
REDIS_URL=redis://redis:6379/0

# MinIO (local in docker-compose)
S3_ENDPOINT=http://minio:9000
S3_BUCKET=vericase-files
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin

# Tika
TIKA_URL=http://tika:9998

# AWS Integration (optional - uncomment to enable)
# USE_AWS_SERVICES=true
# AWS_REGION=$AWS_REGION
# AWS_SECRETS_MANAGER_AI_KEYS=vericase/ai-api-keys

# Feature flags
ENABLE_AI_AUTO_CLASSIFY=false
ENABLE_AI_DATASET_INSIGHTS=false
PYTHONUNBUFFERED=1
DEV_NO_AUTH=false
EOF

# Save credentials for reference
cat > /home/$([ "$OS" = "ubuntu" ] && echo "ubuntu" || echo "ec2-user")/vericase-credentials.txt << EOF
VeriCase Credentials
====================
Generated: $(date)

Admin Email: admin@vericase.com
Admin Password: $ADMIN_PASSWORD
JWT Secret: $JWT_SECRET

API URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):8010
MinIO Console: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):9001

To enable AWS services:
1. Edit /opt/vericase/VeriCaseJet/vericase/.env
2. Uncomment USE_AWS_SERVICES and related settings
3. Run: cd /opt/vericase/VeriCaseJet/vericase && docker-compose restart
EOF

# Set ownership
if [ "$OS" = "ubuntu" ]; then
    chown -R ubuntu:ubuntu $APP_DIR
    chown ubuntu:ubuntu /home/ubuntu/vericase-credentials.txt
elif [ "$OS" = "amzn" ]; then
    chown -R ec2-user:ec2-user $APP_DIR
    chown ec2-user:ec2-user /home/ec2-user/vericase-credentials.txt
fi

# Start services
echo "[7/7] Starting services..."
docker-compose -f docker-compose.prod.yml pull
docker-compose -f docker-compose.prod.yml up -d

# Wait for services
echo "Waiting for services to start..."
sleep 30

# Health check
echo ""
echo "=========================================="
echo "VeriCase Bootstrap Complete!"
echo "=========================================="
echo ""
echo "Public IP: $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)"
echo "API URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):8010"
echo ""
echo "Credentials saved to: ~/vericase-credentials.txt"
echo ""
echo "Service Status:"
docker-compose -f docker-compose.prod.yml ps
echo ""
echo "Logs: docker-compose -f docker-compose.prod.yml logs -f"
echo "=========================================="
